CREATE TABLE IF NOT EXISTS UNICID4.CATEGORIA (
	COD_CATEGORIA int NOT NULL AUTO_INCREMENT,
    NOM_CATEGORIA VARCHAR(45) NOT NULL,
    IDF_ATIVO VARCHAR(1) DEFAULT 'S'COMMENT "S-SIM/N-NÃO"
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (COD_CATEGORIA)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS UNICID4.FABRICANTES (
	COD_FABRICANTE INT NOT NULL AUTO_INCREMENT,
    NOM_FABRICANTE VARCHAR(100) NOT NULL,
    SITE_FABRICANTE VARCHAR(250),
    IDF_ATIVO VARCHAR(1) DEFAULT 'S' COMMENT "S-SIM/N-NÃO"
    CONSTRAINT PK_FABRICANTE PRIMARY KEY (COD_FABRICANTE)
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS UNICID4.PRODUTO (
	COD_PRODUTO INT NOT NULL AUTO_INCREMENT,
    NOM_PRODUTO VARCHAR(250) NOT NULL,
    DSC_PRODUTO TEXT,
    COD_BARRA_PRODUTO VARCHAR(13) NOT NULL,
    IMG_PRODUTO VARCHAR(250) NOT NULL,
    EST_PRODUTO INT DEFAULT 0,
    PCO_PRODUTO DECIMAL(10,2) DEFAULT 0,
    IDF_ATIVO VARCHAR(1) DEFAULT 'S' COMMENT "S-SIM/N-NAO"
    COD_FABRICANTE INT NOT NULL,
    COD_CATEGORIA INT NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO),
    CONSTRAINT FK_PRODUTO_2_FABRICANTES
		FOREIGN KEY (COD_FABRICANTE)
			REFERENCES UNICID4.FABRICANTES (COD_FABRICANTE),
	CONSTRAINT FK_PRODUTO_2_CATEGORIA
		FOREIGN KEY (COD_CATEGORIA)
			REFERENCES UNICID4.CATEGORIA (COD_CATEGORIA)
	CONSTRAINT UQ_PRODUTO_COD_BARRA UNIQUE (COD_BARRA_PRODUTO)
) ENGINE=INNODB;