-- **********************************************************************
-- *                                MÉTODO                              *
-- **********************************************************************
-- Criar a tabela TAMANHO_PIZZA
-- Inserir os dados na tabela TAMANHO_PIZZA com base na tabela ITEM usando as colunas NUM_ITEM_PEDIDO e TAMANHO dos pedidos já existentes
-- Remover a coluna TAMANHO da tabela ITEM
-- Remover a FK para a tabela PIZZA
-- Renomear a coluna COD_PIZZA para COD_PRODUTO
-- Criar a tabela PRODUTO
-- Inserir os dados na tabela PRODUTO com base na tabela de PIZZA com as colunas COD_PIZZA e NOME_PIZZA
-- Criar a FK ta tabela ITEM para a Tabela PRODUTO
-- Remover a FK da tabela PIZZA_USA_INGREDIENTE para a tabela PIZZA
-- Remover a PK da tabela PIZZA_USA_INGREDIENTE
-- Renomear a coluna COD_PIZZA para COD_PRODUTO
-- Recriar a PK da tabela PIZZA_USA_INGREDIENTE
-- Alterar a tabela PIZZA
--    Remover o AUTO_INCREMENT
--    Remover a PK
--    Renomear a coluna COD_PIZZA para COD_PRODUTO e adicionar o AUTO_INCREMENT e PK
--    Criar uma FK para a tabela PRODUTO
--    Remover a coluna NOME_PIZZA
--    Criar uma coluna NUM_PIZZA
--    Atribuir para a coluna NUM_PIZZA o COD_PRODUTO
-- Criar uma FK da tabela PIZZA_USA_INGREDIENTE para a tabela PIZZA com a coluna COD_PRODUTO



-- Criar a tabela TAMANHO_PIZZA
DROP TABLE IF EXISTS PIZZARIA.TAMANHO_PIZZA;
-- Para MySQL 5.7
CREATE TABLE IF NOT EXISTS PIZZARIA.TAMANHO_PIZZA (
    NUM_ITEM_PEDIDO     INT         NOT NULL,
    IDF_TAMANHO_PIZZA   VARCHAR(1)  NOT NULL COMMENT "F - FEMININO / M - MASCULINO",
    CONSTRAINT PK_TAMANHO_PIZZA PRIMARY KEY (NUM_ITEM_PEDIDO),
    CONSTRAINT FK_TAMANHO_PIZZA_2_ITEM FOREIGN KEY (NUM_ITEM_PEDIDO) REFERENCES ITEM (NUM_ITEM_PEDIDO)
) ENGINE=INNODB;

-- Para MySQL 8
-- CREATE TABLE IF NOT EXISTS PIZZARIA.TAMANHO_PIZZA (
--     NUM_ITEM_PEDIDO     INT         NOT NULL,
--     IDF_TAMANHO_PIZZA   VARCHAR(1)  NOT NULL COMMENT "F - FEMININO / M - MASCULINO" CHECK (IDF_TAMANHO_PIZZA IN ('B','I')),
--     CONSTRAINT PK_TAMANHO_PIZZA PRIMARY KEY (NUM_ITEM_PEDIDO),
--     CONSTRAINT FK_TAMANHO_PIZZA_2_ITEM FOREIGN KEY (NUM_ITEM_PEDIDO) REFERENCES ITEM (NUM_ITEM_PEDIDO),
-- ) ENGINE=INNODB;

-- Inserir os dados na tabela TAMANHO_PIZZA com base na tabela ITEM usando as colunas NUM_ITEM_PEDIDO e TAMANHO dos pedidos já existentes
INSERT INTO PIZZARIA.TAMANHO_PIZZA (NUM_ITEM_PEDIDO, IDF_TAMANHO_PIZZA) SELECT NUM_ITEM_PEDIDO, TAMANHO FROM PIZZARIA.ITEM;

-- Remover a coluna TAMANHO da tabela ITEM
ALTER TABLE PIZZARIA.ITEM DROP COLUMN TAMANHO;

-- Remover a FK para a tabela PIZZA
ALTER TABLE PIZZARIA.ITEM DROP FOREIGN KEY FK_ITEM_2_PIZZA;

-- Renomear a coluna COD_PIZZA para COD_PRODUTO
-- Para MySQL 5.7
ALTER TABLE PIZZARIA.ITEM CHANGE COLUMN COD_PIZZA COD_PRODUTO INT NOT NULL;
-- Para MySQL 8
-- ALTER TABLE PIZZARIA.ITEM RENAME COLUMN COD_PIZZA TO COD_PRODUTO;

-- Criar a tabela PRODUTO
DROP TABLE IF EXISTS PIZZARIA.PRODUTO;
CREATE TABLE IF NOT EXISTS PIZZARIA.PRODUTO (
    COD_PRODUTO INT             NOT NULL    AUTO_INCREMENT,
    NOM_PRODUTO VARCHAR(250)    NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
) ENGINE=INNODB;

-- Inserir os dados na tabela PRODUTO com base na tabela de PIZZA com as colunas COD_PIZZA e NOME_PIZZA
INSERT INTO PIZZARIA.PRODUTO (COD_PRODUTO, NOM_PRODUTO) SELECT COD_PIZZA, NOME_PIZZA FROM PIZZARIA.PIZZA;

-- Criar a FK ta tabela ITEM para a Tabela PRODUTO
ALTER TABLE PIZZARIA.ITEM ADD CONSTRAINT FK_ITEM_2_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PIZZARIA.PRODUTO (COD_PRODUTO);

-- Remover a FK da tabela PIZZA_USA_INGREDIENTE para a tabela PIZZA
ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE DROP FOREIGN KEY FK_PIZZA_USA_INGREDIENTE_2_PIZZA;

-- Remover a PK da tabela PIZZA_USA_INGREDIENTE
ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE DROP PRIMARY KEY;

-- Renomear a coluna COD_PIZZA para COD_PRODUTO
-- Para MySQL 5.7
ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE CHANGE COLUMN COD_PIZZA COD_PRODUTO INT NOT NULL;
-- Para MySQL 8
-- ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE RENAME COLUMN COD_PIZZA TO COD_PRODUTO;

-- Recriar a PK da tabela PIZZA_USA_INGREDIENTE
ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE ADD CONSTRAINT PK_PIZZA_USA_INGREDIENTE PRIMARY KEY (COD_PRODUTO, COD_INGREDIENTE);

-- Alterar a tabela PIZZA
--    Remover o AUTO_INCREMENT
ALTER TABLE PIZZARIA.PIZZA MODIFY COLUMN COD_PIZZA INT NOT NULL;

--    Remover a PK
ALTER TABLE PIZZARIA.PIZZA DROP PRIMARY KEY;

--    Renomear a coluna COD_PIZZA para COD_PRODUTO e adicionar o AUTO_INCREMENT e PK
-- Para MySQL 5.7
ALTER TABLE PIZZARIA.PIZZA CHANGE COLUMN COD_PIZZA COD_PRODUTO INT NOT NULL;
-- Para MySQL 8
-- ALTER TABLE PIZZARIA.PIZZA RENAME COLUMN COD_PIZZA TO COD_PRODUTO;
ALTER TABLE PIZZARIA.PIZZA MODIFY COLUMN COD_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY;

--    Criar uma FK para a tabela PRODUTO
ALTER TABLE PIZZARIA.PIZZA ADD CONSTRAINT FK_PIZZA_2_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PIZZARIA.PRODUTO (COD_PRODUTO);

--    Remover a coluna NOME_PIZZA
ALTER TABLE PIZZARIA.PIZZA DROP COLUMN NOME_PIZZA;

--    Criar uma coluna NUM_PIZZA
ALTER TABLE PIZZARIA.PIZZA ADD NUM_PIZZA INT;

--    Atribuir para a coluna NUM_PIZZA o COD_PRODUTO e adicionar NOT NULL
UPDATE PIZZARIA.PIZZA SET
       NUM_PIZZA = COD_PRODUTO
 WHERE COD_PRODUTO > 0;
 
ALTER TABLE PIZZARIA.PIZZA MODIFY COLUMN NUM_PIZZA INT NOT NULL;

-- Criar uma FK da tabela PIZZA_USA_INGREDIENTE para a tabela PIZZA com a coluna COD_PRODUTO
ALTER TABLE PIZZARIA.PIZZA_USA_INGREDIENTE ADD CONSTRAINT FK_PIZZA_USA_INGREDIENTE_2_PIZZA FOREIGN KEY (COD_PRODUTO) REFERENCES PIZZARIA.PIZZA (COD_PRODUTO);



