-- https://saopaulopizzas.com.br/quem_somos

DROP DATABASE IF EXISTS PIZZARIA;
CREATE DATABASE IF NOT EXISTS PIZZARIA;

DROP TABLE IF EXISTS PIZZARIA.CLIENTE;
CREATE TABLE PIZZARIA.CLIENTE (
	COD_CLIENTE 			INT 			NOT NULL 	AUTO_INCREMENT,
	NOME_CLIENTE 			VARCHAR(150) 	NOT NULL,
	RUA 					VARCHAR(150) 	NOT NULL,
	NUMERO 					VARCHAR(20) 	NOT NULL,
	COMPLEMENTO 			VARCHAR(30),
	SENHA 					VARCHAR(100) 	NOT NULL,
	EMAIL 					VARCHAR(100) 	NOT NULL,
	CPF 					VARCHAR(11) 	NOT NULL,
	IDF_SEXO 				VARCHAR(1) 		COMMENT "F - FEMININO / M - MASCULINO",
	IDF_ATIVO 				VARCHAR(1) 		DEFAULT 'S' COMMENT "S - SIM / N - NÃO",
	CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE),
	CONSTRAINT CK_CLIENTE_SEXO  CHECK (IDF_SEXO  IN ('F', 'M')),
	CONSTRAINT CK_CLIENTE_ATIVO CHECK (IDF_ATIVO IN ('S', 'N'))
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.TELEFONE_CLIENTE;
CREATE TABLE PIZZARIA.TELEFONE_CLIENTE (
	COD_CLIENTE 				INT 			NOT NULL,
	TELEFONE 					VARCHAR(11) 	NOT NULL,
	CONSTRAINT PK_TELEFONE_CLIENTE PRIMARY KEY (COD_CLIENTE,TELEFONE),
	CONSTRAINT FK_TELEFONE_CLIENTE_2_CLIENTE 
		FOREIGN KEY (COD_CLIENTE) REFERENCES PIZZARIA.CLIENTE (COD_CLIENTE)
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.PIZZA;
CREATE TABLE PIZZARIA.PIZZA (
	COD_PIZZA 				INT 			NOT NULL AUTO_INCREMENT,
	NOME_PIZZA 				VARCHAR(150) 	NOT NULL,
	CONSTRAINT PK_PIZZA PRIMARY KEY (COD_PIZZA)
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.TAMANHO_PIZZA;
CREATE TABLE PIZZARIA.TAMANHO_PIZZA (
	COD_PIZZA 				INT 				NOT NULL,
	DESC_TAMANHO_PIZZA 		VARCHAR(20) 		NOT NULL,
	PRECO_TAMANHO_PIZZA 	DECIMAL(10,2) 		NOT NULL DEFAULT 0,
	PRIMARY KEY (COD_PIZZA,DESC_TAMANHO_PIZZA),
	CONSTRAINT FK_TAMANHO_PIZZA_2_PIZZA 
		FOREIGN KEY (COD_PIZZA) REFERENCES PIZZARIA.PIZZA (COD_PIZZA)
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.PEDIDO;
CREATE TABLE PIZZARIA.PEDIDO (
	NUM_PEDIDO 					INT 			NOT NULL AUTO_INCREMENT,
	DTA_HOR_ABERTURA_PEDIDO 	DATETIME 		NOT NULL,
    DTA_HOR_FECHAMENTO_PEDIDO	DATETIME,
	IDF_ORIGEM_PEDIDO 			VARCHAR(1) 		NOT NULL COMMENT "1 - TELEFONE  / 2 - BALCÃO / 3 - INTERNET",
	IDF_FORMA_PAGAMENTO			VARCHAR(1) 		NOT NULL COMMENT "1 - DINHEIRO  / 2 - CHEQUE / 3 - CARTÃO DE DÉBITO / 4 - CARTÃO DE CRÉDITO",
	COD_CLIENTE 				INT 			NOT NULL,
	CONSTRAINT PK_PEDIDO PRIMARY KEY (NUM_PEDIDO),
	CONSTRAINT FK_PEDIDO_2_CLIENTE 
		FOREIGN KEY (COD_CLIENTE) REFERENCES PIZZARIA.CLIENTE (COD_CLIENTE),
	CONSTRAINT CK_PEDIDO_ORIGEM          CHECK (IDF_ORIGEM_PEDIDO   BETWEEN 1 AND 3),
	CONSTRAINT CK_PEDIDO_FORMA_PAGAMENTO CHECK (IDF_FORMA_PAGAMENTO BETWEEN 1 AND 4)
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.CONTEM;
CREATE TABLE PIZZARIA.CONTEM (
	NUM_PEDIDO 			INT 			NOT NULL,
	COD_PIZZA 			INT 			NOT NULL,
	DESC_TAMANHO_PIZZA 	VARCHAR(20) 	NOT NULL,
	QUANTIDADE 			DECIMAL(5,2) 	DEFAULT 1,
	PRECO 				DECIMAL(10,2) 	DEFAULT 0,
	CONSTRAINT PK_CONTEM PRIMARY KEY (NUM_PEDIDO, COD_PIZZA, DESC_TAMANHO_PIZZA),
	CONSTRAINT FK_CONTEM_2_PEDIDO 
		FOREIGN KEY (NUM_PEDIDO) REFERENCES PIZZARIA.PEDIDO (NUM_PEDIDO),
	CONSTRAINT FK_CONTEM_2_TAMANHO_PIZZA 
		FOREIGN KEY (COD_PIZZA, DESC_TAMANHO_PIZZA) REFERENCES PIZZARIA.TAMANHO_PIZZA (COD_PIZZA, DESC_TAMANHO_PIZZA)
) ENGINE=INNODB;

DROP TABLE IF EXISTS PIZZARIA.INGREDIENTES_PIZZA;
CREATE TABLE IF NOT EXISTS PIZZARIA.INGREDIENTES_PIZZA (
	COD_PIZZA			INT				NOT NULL,
	INGREDIENTE			VARCHAR(150)	NOT NULL,
	CONSTRAINT PK_INGREDIENTES_PIZZA PRIMARY KEY (COD_PIZZA, INGREDIENTE),
	CONSTRAINT FK_INGREDIENTES_PIZZA_2_PIZZA
		FOREIGN KEY (COD_PIZZA) REFERENCES PIZZARIA.PIZZA (COD_PIZZA)
) ENGINE=INNODB;
