CREATE DATABASE IF NOT EXISTS UNICID4;

DROP TABLE IF EXISTS UNICID4.PESSOA;
CREATE TABLE IF NOT EXISTS UNICID4.PESSOA(
	COD_TIPO_PESSOA INT 		 NOT NULL,
    DSC_TIPO_PESSOA VARCHAR(250) NOT NULL,
    CONSTRAINT	PK_PESSOA PRIMARY KEY (COD_PESSOA)
);
DROP TABLE IF EXISTS UNICID4.PESSOA;
CREATE TABLE IF NOT EXISTS UNICID4.PESSOA(
	COD_PESSOA		INT			NOT NULL,
    NOM_PESSOA 		VARCHAR(250)NOT NULL,
    CPF_PESSOA 		VARCHAR(16),
    RG_PESSOA 		VARCHAR(12),
    EMAIL_PESSOA 	VARCHAR(100),
    DTA_NASC_PESSOA	DATE		NOT NULL,
    IDF_SEXO		VARCHAR(1) 	NOT NULL,
    IDF_ATIVO		VARCHAR(1) 	NOT NULL,
    COD_TIPO_PESSOA	INT 		NOT NULL,
    CONSTRAINT	PK_PESSOA PRIMARY KEY (COD_PESSOA),
    CONSTRAINT FK_PESSOA_2_TIPO_PESSOA
    FOREIGN KEY (COD_TIPO_PESSOA_P)
		REFERENCES UNICID4.TIPO_PESSOA (COD_TIPO_PESSOA)
    ) ENGINE=INNODB;